services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    volumes:
      - zookeeper-data:/bitnami

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    environment:
      - KAFKA_BROKERCONNECT=kafka:29092,kafka-2:29093,kafka-3:29094
    ports:
      - 9000:9000
    depends_on:
      - kafka
      - kafka-2
      - kafka-3

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=2
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - 9092:9092
    volumes:
      - kafka-data:/bitnami
    depends_on:
      - zookeeper

  kafka-2:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://:29093,EXTERNAL://:9093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-2:29093,EXTERNAL://kafka-2:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=2
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - 9093:9093
    volumes:
      - kafka-data-2:/bitnami
    depends_on:
      - zookeeper

  kafka-3:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://:29094,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-3:29094,EXTERNAL://kafka-3:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=2
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - 9094:9094
    volumes:
      - kafka-data-3:/bitnami
    depends_on:
      - zookeeper

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway.dockerfile
    environment:
      - KAFKA_ANONYMOUS=false
      - KAFKA_BROKERS=kafka.kafka.svc.cluster.local:9092
      - KAFKA_USERNAME=user1
      - KAFKA_PASSWORD=kZbbm7TUBk
    ports:
      - 3000:3000
    depends_on:
      - kafka
      - kafka-2
      - kafka-3

  auth-service:
    build:
      context: .
      dockerfile: auth-service.dockerfile
    environment:
      - KAFKA_ANONYMOUS=false
      - KAFKA_BROKERS=kafka.kafka.svc.cluster.local:9092
      - KAFKA_USERNAME=user1
      - KAFKA_PASSWORD=kZbbm7TUBk
    depends_on:
      - kafka
      - kafka-2
      - kafka-3

  movie-service:
    build:
      context: .
      dockerfile: movie-service.dockerfile
    environment:
      - KAFKA_ANONYMOUS=false
      - KAFKA_BROKERS=kafka.kafka.svc.cluster.local:9092
      - KAFKA_USERNAME=user1
      - KAFKA_PASSWORD=kZbbm7TUBk
    depends_on:
      - kafka
      - kafka-2
      - kafka-3

  log-service:
    build:
      context: .
      dockerfile: log-service.dockerfile
    environment:
      - KAFKA_ANONYMOUS=false
      - KAFKA_BROKERS=kafka.kafka.svc.cluster.local:9092
      - KAFKA_USERNAME=user1
      - KAFKA_PASSWORD=kZbbm7TUBk
    depends_on:
      - kafka
      - kafka-2
      - kafka-3

volumes:
  zookeeper-data:
    driver: local
  kafka-data:
    driver: local
  kafka-data-2:
    driver: local
  kafka-data-3:
    driver: local
