apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-service
  template:
    metadata:
      labels:
        app: log-service
    spec:
      containers:
      - name: log-service
        image: qytela/log-service:dev-0.1
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: apps-configmap
      nodeSelector:
        role: worker
